version: '2'
services:
    nginx:
        image: nginx:1.17.3
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./etc/nginx/conf.d:/etc/nginx/conf.d
            - ./data/letsencrypt:/etc/letsencrypt
        networks:
            - nginx

networks:
    nginx:
        driver: bridge
